# serverless.yml
service: silam-air-quality-sns-processing
plugins:
  - serverless-python-requirements
  - serverless-wsgi


custom:
  wsgi:
    app: app.silam_air_quality_process
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1 # AWS landsat8 bucket in us-west-2 (oregeon)
  timeout: 30 # optional, in seconds, default is 6
  memorySize: 1024 # optional, in MB, default is 1024

iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::landsat-pds/*"
       - "arn:aws:s3:::sentinel-cogs/*"
       - "arn:aws:s3:::fmi-opendata-silam-surface-netcdf/*"

  -  Effect: "Allow"
     Action:
       - "s3:PutObject"
     Resource:
       - "arn:aws:s3:::silam-air-quality/*"

apiGateway:
  binaryMediaTypes:
    - '*/*'

layers: # An optional list Lambda Layers to use
  - arn:aws:lambda:us-east-1:552188055668:layer:geolambda:4

functions:
  dispatcher:
    handler: wsgi_handler.handler
    events:
      - sns:  arn:aws:sns:eu-west-1:916174725480:new-fmi-opendata-silam-surface-netcdf